//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDImoestudante.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class alojamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public alojamento()
        {
            this.aluguers = new HashSet<aluguer>();
        }
    
        public int idAlojamento { get; set; }
        public int idTipologia { get; set; }
        public int idTipoAlojamento { get; set; }
        public int idMorada { get; set; }
        public int idEstado { get; set; }
        public Nullable<int> avaliacao { get; set; }
        public string descricao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aluguer> aluguers { get; set; }
        public virtual estado estado { get; set; }
        public virtual morada morada { get; set; }
        public virtual tipoAlojamento tipoAlojamento { get; set; }
        public virtual tipologia tipologia { get; set; }
    }
}
