//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDImoestudante.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aluguer
    {
        public int idAluguer { get; set; }
        public int idAlojamento { get; set; }
        public int idUserAgente { get; set; }
        public int idUserSenhorio { get; set; }
        public int idUserInquilino { get; set; }
        public System.DateTime dataInicio { get; set; }
        public System.DateTime dataFim { get; set; }
        public int valoRenda { get; set; }
    
        public virtual alojamento alojamento { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual user user2 { get; set; }
    }
}
