//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDImoestudante.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class areaCurso
    {
        public int idArea { get; set; }
        public int idCurso { get; set; }
        public string nomeArea { get; set; }
    
        public virtual curso curso { get; set; }
    }
}
