//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDImoestudante.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class morada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public morada()
        {
            this.alojamentoes = new HashSet<alojamento>();
            this.instituicaoEnsinoes = new HashSet<instituicaoEnsino>();
        }
    
        public int idMorada { get; set; }
        public int idPais { get; set; }
        public string cidade { get; set; }
        public string rua { get; set; }
        public int codigoPostal { get; set; }
        public Nullable<int> numero { get; set; }
        public Nullable<int> andar { get; set; }
        public string descAndar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alojamento> alojamentoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<instituicaoEnsino> instituicaoEnsinoes { get; set; }
        public virtual pai pai { get; set; }
    }
}
