//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDImoestudante.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.aluguers = new HashSet<aluguer>();
            this.aluguers1 = new HashSet<aluguer>();
            this.aluguers2 = new HashSet<aluguer>();
            this.contactoes = new HashSet<contacto>();
        }
    
        public int idUser { get; set; }
        public int idTipo { get; set; }
        public int idGenero { get; set; }
        public int idMorada { get; set; }
        public int idPais { get; set; }
        public int idCurso { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> dataNascimento { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string apiKey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aluguer> aluguers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aluguer> aluguers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aluguer> aluguers2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contacto> contactoes { get; set; }
        public virtual curso curso { get; set; }
        public virtual genero genero { get; set; }
        public virtual pai pai { get; set; }
    }
}
